keys:
  - &users '':
      - &admin_douglas 251DD91D6924C206B70EBB93F2DDEC00E62953A3
  - &hosts '':
      - &host_fox_old age1g92zj25h7yucv8nmswcvhat7vqsnk3zlky32dyfk5k2973au04aqtmxc9q
      - &host_fox age15t86k2t49ls4kg2ugv97gmrpwy8tpj4md06qx3tp4yhfvdazj5kqzmcg8g
      - &host_beast_home_mayle_org age1vh4mwu86c3q8h2qg30tmjr9pex58ulpg88cvxcnhkpcw6s6fuf0s7hn8uk
creation_rules:
  - path_regex: secrets/secrets\.yaml
    key_groups:
      - pgp:
          - *admin_douglas
        age:
          - *host_beast_home_mayle_org
  - path_regex: secrets/fox\.yaml
    key_groups:
      - pgp:
          - *admin_douglas
        age:
          - *host_fox_old
          - *host_fox
