# Generated by ./update.sh - do not update manually!
# Last updated: 2023-05-02
{
  compatList = {
    rev = "74ee6aaa8079f05adf9b4c262bbed2b090a2ec15";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1416";
    hash = "sha256:0z7dji4dcakpy2ikpdmbrfrxn35whqffvzsvy00r2kkbadg38ww4";
  };

  ea = {
    version = "3575";
    distHash = "sha256-D1O8ao6W4QRvgTJrQ10Mf18XnHHJVISPoqCm/sphkFY=";
    fullHash = "sha256-4fGw+IWV+1D/GecqIz8y7vBBMyunUl0xUYLexgKePKk=";
  };
}
