# Generated by ./update.sh - do not update manually!
# Last updated: 2023-05-02
{
  compatList = {
    rev = "74ee6aaa8079f05adf9b4c262bbed2b090a2ec15";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1416";
    hash = "sha256:0z7dji4dcakpy2ikpdmbrfrxn35whqffvzsvy00r2kkbadg38ww4";
  };

  ea = {
    version = "3709";
    distHash = "sha256-30nyH4nZ5XsUyQ1+GMLXBdcu4Om6Xt9WSCGmnc2fEHg=";
    fullHash = "sha256-AxlPov3JquUCLmMZI32bFQ/JK+f6e3kpxneuBqvO+bU=";
    timezoneHash = "sha256-yv8ykEYPu9upeXovei0u16iqQ7NasH6873KnQy4+KwI=";
  };
}
